grep backup_dir_on_cn_dn_host tc7_iotdb_5317_mig_disable.sh                                      |head -1
grep backup_dir_on_cn_dn_host tc8_mig2_mig_unknown_restart_unknown.sh                            |head -1
grep backup_dir_on_cn_dn_host tc9_mig3_3dr_unknown.sh                                            |head -1
grep backup_dir_on_cn_dn_host tc901_jira994.sh                                                   |head -1
grep backup_dir_on_cn_dn_host tc10_mig_3dr_readonly.sh                                           |head -1
grep backup_dir_on_cn_dn_host tc11_mig_to_readonly.sh                                            |head -1
grep backup_dir_on_cn_dn_host tc12_mig_to_unknown.sh                                             |head -1
grep backup_dir_on_cn_dn_host tc13_miging_stop_dest.sh                                           |head -1
grep backup_dir_on_cn_dn_host tc14_all_rep_mig_check_data.sh                                     |head -1
grep backup_dir_on_cn_dn_host tc15_mig_schemaregion_stop_desc_dn.sh                              |head -1
grep backup_dir_on_cn_dn_host tc1501_mig_schemaregion_stop_desc_dn.sh                            |head -1
grep backup_dir_on_cn_dn_host tc1502_mig_sr_stop_dest_jira961.sh                                 |head -1
grep backup_dir_on_cn_dn_host tc1503_jira960_restart_2dn.sh                                      |head -1
grep backup_dir_on_cn_dn_host tc16_mig_schemaregion_stop_desc_dn.sh                              |head -1
grep backup_dir_on_cn_dn_host tc17_timechodb_650_check_dest_comp.sh                              |head -1
grep backup_dir_on_cn_dn_host tc18_mig_1readonly_1unknown_to_running.sh                          |head -1
grep backup_dir_on_cn_dn_host tc19_con_mig_1readonly_1unknown_to_running.sh                      |head -1
grep backup_dir_on_cn_dn_host tc20_mig_same_orig_to_diff_dest.sh                                 |head -1
grep backup_dir_on_cn_dn_host tc21_mig_2_orig_to_same_dest.sh                                    |head -1
grep backup_dir_on_cn_dn_host tc22_mig_region_exec_2time.sh                                      |head -1
grep backup_dir_on_cn_dn_host tc23_mig_region_stop_coord.sh                                      |head -1
grep backup_dir_on_cn_dn_host tc24_mig_region_kill_coord.sh                                      |head -1
grep backup_dir_on_cn_dn_host tc25_mig_region_stop_dest_dn.sh                                    |head -1
grep backup_dir_on_cn_dn_host tc26_mig_region_kill9_dest_dn.sh                                   |head -1
grep backup_dir_on_cn_dn_host tc2601_mig_region_kill9_dest_dn_tsfile_bad_jira1044.sh             |head -1
grep backup_dir_on_cn_dn_host tc2602_mig_snapshot_stop_dest_dn.sh                                |head -1
grep backup_dir_on_cn_dn_host tc27_mig_region_stop_cn_leader.sh                                  |head -1
grep backup_dir_on_cn_dn_host tc28_mig_region_kill_cn_leader.sh                                  |head -1
grep backup_dir_on_cn_dn_host tc29_mig_schema_data_priv.sh                                       |head -1
grep backup_dir_on_cn_dn_host tc30_mig_sr_del_timeseries.sh                                      |head -1
grep backup_dir_on_cn_dn_host tc31_mig_sr_create_ts.sh                                           |head -1
grep backup_dir_on_cn_dn_host tc32_illegal_mig_sql.sh                                            |head -1
grep backup_dir_on_cn_dn_host tc33_mig_dr_del_data.sh                                            |head -1
grep backup_dir_on_cn_dn_host tc34_mig_dr_insert_data.sh                                         |head -1
grep backup_dir_on_cn_dn_host tc35_mig_drop_db.sh                                                |head -1
grep backup_dir_on_cn_dn_host tc36_mig_drop_other_db.sh                                          |head -1
grep backup_dir_on_cn_dn_host tc37_mig_set_ttl.sh                                                |head -1
grep backup_dir_on_cn_dn_host tc38_adding_removing.sh                                            |head -1
grep backup_dir_on_cn_dn_host tc39_mig_speed_is_0.sh                                             |head -1
grep backup_dir_on_cn_dn_host tc40_mig_speed_is_64MiB.sh                                         |head -1
grep backup_dir_on_cn_dn_host tc41_add_peer_coord_exp.sh                                         |head -1
grep backup_dir_on_cn_dn_host tc4101_jira1217.sh                                                 |head -1
grep backup_dir_on_cn_dn_host tc42_add_peer_stop_dest_dn.sh                                      |head -1
grep backup_dir_on_cn_dn_host tc43_add_peer_stop_cn_coord.sh                                     |head -1
grep backup_dir_on_cn_dn_host tc44_add_peer_stop_cn_remove-coord.sh                              |head -1
grep backup_dir_on_cn_dn_host tc45_add_peer_stop_mig-region_2dn.sh                               |head -1
grep backup_dir_on_cn_dn_host tc46_add_peer_stop_mig_region_all_dn.sh                            |head -1
grep backup_dir_on_cn_dn_host tc47_add_peer_stop_mig_region_all_dn_cn_leader.sh                  |head -1
grep backup_dir_on_cn_dn_host tc48_aft_add_peer_kill_dest_dn_pid.sh                              |head -1
grep backup_dir_on_cn_dn_host tc49_aft_add_peer_kill_coord_dn_pid.sh                             |head -1
grep backup_dir_on_cn_dn_host tc50_aft_add_peer_kill_source_dn.sh                                |head -1
grep backup_dir_on_cn_dn_host tc51_aft_add_peer_kill_dn_cn.sh                                    |head -1
grep backup_dir_on_cn_dn_host tc52_mig_sr_alter_timeseries.sh                                    |head -1
grep backup_dir_on_cn_dn_host tc53_mig_comping.sh                                                |head -1
grep backup_dir_on_cn_dn_host tc56_TIMECHODB-947.sh                                              |head -1
grep backup_dir_on_cn_dn_host tc57_timechodb_857_985.sh                                          |head -1
